# OS
UBUNTU_VERSION=22.04

# Python
PYTHON_VERSION=3.11

# VS Code
VSCODE_VERSION=1.124.2
VSCODE_GIT_HASH=6928394f91b684055b873eecb8bc281365131f1c

# Init
S6_OVERLAY_VERSION=3.2.3.0

# CUDA compile layer
CUDA_MAJOR=12
CUDA_MINOR=2