# OS
UBUNTU_VERSION=22.04

# Python
PYTHON_VERSION=3.11

# VS Code
VSCODE_VERSION=1.125.1
VSCODE_GIT_HASH=fcf604774b9f2674b473065736ee75077e256353

# Init
S6_OVERLAY_VERSION=3.2.3.0

# CUDA compile layer
CUDA_MAJOR=12
CUDA_MINOR=2