apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
    - name: monitoring
      port: 9090
      targetPort: monitoring
  type: LoadBalancer