#!/command/with-contenv bash

set -euo pipefail

echo "[cont-init] Configuring nginx..."

# -----------------------------
# Defaults
# -----------------------------

: "${SVC_PORT:=8888}"
: "${NB_PREFIX:=/}"
: "${SERVE_DIR:=/home/jovyan}"
: "${ENABLE_CONNECT_PROXY:=1}"


# -----------------------------
# Normalize SERVE_DIR
# -----------------------------

# collapse duplicate slashes
SERVE_DIR="$(echo "${SERVE_DIR}" | sed 's#//*#/#g')"

# remove trailing slash except root
SERVE_DIR="$(echo "${SERVE_DIR}" | sed 's#/$##')"

[ -z "${SERVE_DIR}" ] && SERVE_DIR="/home/jovyan"


echo "[cont-init] Creating serve directory: ${SERVE_DIR}"

install -d \
    -o jovyan \
    -g shared \
    -m 775 \
    "${SERVE_DIR}"


# nginx alias requires trailing slash
SERVE_DIR_ALIAS="${SERVE_DIR}/"


# -----------------------------
# Normalize NB_PREFIX
# -----------------------------

# ensure leading slash
NB_PREFIX="/${NB_PREFIX}"

# collapse duplicate slashes
NB_PREFIX="$(echo "${NB_PREFIX}" | sed 's#//*#/#g')"

# remove trailing slash
NB_PREFIX="$(echo "${NB_PREFIX}" | sed 's#/$##')"


# root prefix special case
if [ -z "${NB_PREFIX}" ]; then
    NB_PREFIX="/"
fi


# For regex locations (/ should become empty)
if [ "${NB_PREFIX}" = "/" ]; then
    NB_PREFIX_REGEX=""
else
    NB_PREFIX_REGEX="${NB_PREFIX}"
fi


echo "[cont-init] SVC_PORT=${SVC_PORT}"
echo "[cont-init] NB_PREFIX=${NB_PREFIX}"
echo "[cont-init] SERVE_DIR=${SERVE_DIR}"


# -----------------------------
# Export for confd
# -----------------------------

export \
    SVC_PORT \
    NB_PREFIX \
    NB_PREFIX_REGEX \
    SERVE_DIR \
    SERVE_DIR_ALIAS \
    ENABLE_CONNECT_PROXY


# -----------------------------
# Render
# -----------------------------

confd \
    -backend env \
    -onetime


nginx -t


echo "[cont-init] Configuring nginx... Done"